<?php
/**
 * AuthChainElementTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Mainnet
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0.
 *
 * The version of the OpenAPI document: 2.7.25
 * Contact: hello@mainnet.cash
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mainnet;

use PHPUnit\Framework\TestCase;

/**
 * AuthChainElementTest Class Doc Comment
 *
 * @category    Class
 * @description AuthChainElement
 * @package     Mainnet
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AuthChainElementTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AuthChainElement"
     */
    public function testAuthChainElement()
    {
    }

    /**
     * Test attribute "tx_hash"
     */
    public function testPropertyTxHash()
    {
    }

    /**
     * Test attribute "content_hash"
     */
    public function testPropertyContentHash()
    {
    }

    /**
     * Test attribute "uris"
     */
    public function testPropertyUris()
    {
    }

    /**
     * Test attribute "https_url"
     */
    public function testPropertyHttpsUrl()
    {
    }
}
