<?php
/**
 * ElectrumRawTransactionTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Mainnet
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0.
 *
 * The version of the OpenAPI document: 2.4.1
 * Contact: hello@mainnet.cash
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mainnet;

use PHPUnit\Framework\TestCase;

/**
 * ElectrumRawTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description ElectrumRawTransaction
 * @package     Mainnet
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ElectrumRawTransactionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ElectrumRawTransaction"
     */
    public function testElectrumRawTransaction()
    {
    }

    /**
     * Test attribute "blockhash"
     */
    public function testPropertyBlockhash()
    {
    }

    /**
     * Test attribute "blocktime"
     */
    public function testPropertyBlocktime()
    {
    }

    /**
     * Test attribute "confirmations"
     */
    public function testPropertyConfirmations()
    {
    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {
    }

    /**
     * Test attribute "hex"
     */
    public function testPropertyHex()
    {
    }

    /**
     * Test attribute "locktime"
     */
    public function testPropertyLocktime()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }

    /**
     * Test attribute "txid"
     */
    public function testPropertyTxid()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "vin"
     */
    public function testPropertyVin()
    {
    }

    /**
     * Test attribute "vout"
     */
    public function testPropertyVout()
    {
    }
}
