<?php
/**
 * EscrowInfoResponseTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Mainnet
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@mainnet.cash
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mainnet;

use PHPUnit\Framework\TestCase;

/**
 * EscrowInfoResponseTest Class Doc Comment
 *
 * @category    Class
 * @description EscrowInfoResponse
 * @package     Mainnet
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EscrowInfoResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EscrowInfoResponse"
     */
    public function testEscrowInfoResponse()
    {
    }

    /**
     * Test attribute "escrow_contract_id"
     */
    public function testPropertyEscrowContractId()
    {
    }

    /**
     * Test attribute "script"
     */
    public function testPropertyScript()
    {
    }

    /**
     * Test attribute "parameters"
     */
    public function testPropertyParameters()
    {
    }

    /**
     * Test attribute "cashaddr"
     */
    public function testPropertyCashaddr()
    {
    }

    /**
     * Test attribute "buyer_addr"
     */
    public function testPropertyBuyerAddr()
    {
    }

    /**
     * Test attribute "arbiter_addr"
     */
    public function testPropertyArbiterAddr()
    {
    }

    /**
     * Test attribute "seller_addr"
     */
    public function testPropertySellerAddr()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "nonce"
     */
    public function testPropertyNonce()
    {
    }
}
