<?php
/**
 * SendResponseTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Mainnet
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0.
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: hello@mainnet.cash
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mainnet;

use PHPUnit\Framework\TestCase;

/**
 * SendResponseTest Class Doc Comment
 *
 * @category    Class
 * @description SendResponse
 * @package     Mainnet
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SendResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SendResponse"
     */
    public function testSendResponse()
    {
    }

    /**
     * Test attribute "tx_id"
     */
    public function testPropertyTxId()
    {
    }

    /**
     * Test attribute "balance"
     */
    public function testPropertyBalance()
    {
    }

    /**
     * Test attribute "explorer_url"
     */
    public function testPropertyExplorerUrl()
    {
    }

    /**
     * Test attribute "token_ids"
     */
    public function testPropertyTokenIds()
    {
    }
}
