<?php
/**
 * SendRequestOptionsTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Mainnet
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0.
 *
 * The version of the OpenAPI document: 1.1.10
 * Contact: hello@mainnet.cash
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mainnet;

use PHPUnit\Framework\TestCase;

/**
 * SendRequestOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description SendRequestOptions
 * @package     Mainnet
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SendRequestOptionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SendRequestOptions"
     */
    public function testSendRequestOptions()
    {
    }

    /**
     * Test attribute "utxo_ids"
     */
    public function testPropertyUtxoIds()
    {
    }

    /**
     * Test attribute "change_address"
     */
    public function testPropertyChangeAddress()
    {
    }

    /**
     * Test attribute "slp_aware"
     */
    public function testPropertySlpAware()
    {
    }

    /**
     * Test attribute "slp_semi_aware"
     */
    public function testPropertySlpSemiAware()
    {
    }

    /**
     * Test attribute "query_balance"
     */
    public function testPropertyQueryBalance()
    {
    }

    /**
     * Test attribute "await_transaction_propagation"
     */
    public function testPropertyAwaitTransactionPropagation()
    {
    }

    /**
     * Test attribute "fee_paid_by"
     */
    public function testPropertyFeePaidBy()
    {
    }

    /**
     * Test attribute "check_token_quantities"
     */
    public function testPropertyCheckTokenQuantities()
    {
    }
}
