<?php
/**
 * SmartBchOverridesTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Mainnet
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0.
 *
 * The version of the OpenAPI document: 0.5.3
 * Contact: hello@mainnet.cash
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mainnet;

use PHPUnit\Framework\TestCase;

/**
 * SmartBchOverridesTest Class Doc Comment
 *
 * @category    Class
 * @description SmartBchOverrides
 * @package     Mainnet
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SmartBchOverridesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SmartBchOverrides"
     */
    public function testSmartBchOverrides()
    {
    }

    /**
     * Test attribute "gas_limit"
     */
    public function testPropertyGasLimit()
    {
    }

    /**
     * Test attribute "gas_price"
     */
    public function testPropertyGasPrice()
    {
    }

    /**
     * Test attribute "max_fee_per_gas"
     */
    public function testPropertyMaxFeePerGas()
    {
    }

    /**
     * Test attribute "max_priority_fee_per_gas"
     */
    public function testPropertyMaxPriorityFeePerGas()
    {
    }

    /**
     * Test attribute "nonce"
     */
    public function testPropertyNonce()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "block_tag"
     */
    public function testPropertyBlockTag()
    {
    }

    /**
     * Test attribute "from"
     */
    public function testPropertyFrom()
    {
    }
}
