<?php
/**
 * SmartbchSep20ApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Mainnet
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0.
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: hello@mainnet.cash
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Mainnet;

use \Mainnet\Configuration;
use \Mainnet\ApiException;
use \Mainnet\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SmartbchSep20ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mainnet
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SmartbchSep20ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for smartBchSep20AllBalances
     *
     * Get all SmartBch SEP20 balances of the wallet.
     *
     */
    public function testSmartBchSep20AllBalances()
    {
    }

    /**
     * Test case for smartBchSep20Balance
     *
     * Get total SmartBch SEP20 token balance of the wallet.
     *
     */
    public function testSmartBchSep20Balance()
    {
    }

    /**
     * Test case for smartBchSep20DepositAddress
     *
     * Get an SmartBch SEP20 deposit address.
     *
     */
    public function testSmartBchSep20DepositAddress()
    {
    }

    /**
     * Test case for smartBchSep20DepositQr
     *
     * Get an SmartBch SEP20 receiving address as a qrcode.
     *
     */
    public function testSmartBchSep20DepositQr()
    {
    }

    /**
     * Test case for smartBchSep20Genesis
     *
     * Get created tokenId back and new SmartBch SEP20 token balance of the wallet.
     *
     */
    public function testSmartBchSep20Genesis()
    {
    }

    /**
     * Test case for smartBchSep20Mint
     *
     * Get created tokenId back and new SmartBch SEP20 token balance of the wallet.
     *
     */
    public function testSmartBchSep20Mint()
    {
    }

    /**
     * Test case for smartBchSep20Send
     *
     * Send some SmartBch SEP20 token amount to a given address.
     *
     */
    public function testSmartBchSep20Send()
    {
    }

    /**
     * Test case for smartBchSep20SendMax
     *
     * Send all available SmartBch SEP20 token funds to a given address.
     *
     */
    public function testSmartBchSep20SendMax()
    {
    }

    /**
     * Test case for smartBchSep20TokenInfo
     *
     * Get information about the SmartBch SEP20 token.
     *
     */
    public function testSmartBchSep20TokenInfo()
    {
    }
}
